[package]
name = "subtype"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "0.99.18" }
num-traits = { version = "0.2.19", optional = true }
serde = { version = "1.0.204", optional = true, features = ["derive"] }
