disallowed-types = [
    #    { path = "std::collections::HashMap", reason = "use rustc_hash::FxHashMap (it's faster)" },
    #    { path = "std::collections::HashSet", reason = "use rustc_hash::FxHashSet (it's faster)" },
]
