[tools]
rust = "stable"

[tasks."build"]
run = "cargo build"

[tasks."fmt"]
run = "cargo fmt --all"

[tasks."lint:code"]
run = "cargo clippy --all-targets --all-features -- -D warnings"

[tasks."lint:docs"]
run = "remark --ignore-path .gitignore --quiet --frail --no-stdout ."

[tasks."lint:deps"]
run = "cargo machete --with-metadata"

[tasks."test:code"]
run = "cargo nextest run"

[tasks."test:docs"]
run = "cargo test --doc"

[tasks."sort:deps"]
run = "cargo sort"

[tasks."watch"]
run = """
#!/usr/bin/env bash
set -euxo pipefail
PWD=$(pwd)
CMD_RAW="nextest run $*"
CMD_NO_WHITESPACE="$(echo -e "${CMD_RAW}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
cargo watch --clear --watch "$PWD" --exec "$CMD_NO_WHITESPACE"
"""

[tasks."check"]
run = "cargo check --all-targets"

[tasks."fix"]
run = "cargo fix --workspace --allow-dirty --allow-staged"
