[tools]
rust = "stable"

[tasks.build]
run = "cargo build"

[tasks.lint]
run = "cargo clippy --all-targets --all-features {{args}} -- -D warnings"

[tasks.test]
run = "cargo nextest run"

[tasks.watch]
run = """
#!/usr/bin/env bash
set -euxo pipefail
PWD=$(pwd)
CMD_RAW="nextest run $*"
CMD_NO_WHITESPACE="$(echo -e "${CMD_RAW}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
cargo watch --clear --watch "$PWD" --exec "$CMD_NO_WHITESPACE"
"""

[tasks.check]
run = "cargo check --all-targets"

[tasks.fix]
run = "cargo fix --workspace --allow-dirty --allow-staged"
