[package]
name = "tasks"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
subtype = { path = "..", features = ["time"] }
derive_more = { version = "2.1.1", features = ["full"] }
anyhow = { version = "1.0.86" }
derive_builder = "0.20.0"
url = "2.5.2"
url-macro = "0.2.3"
time = "0.3.36"
